name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan # or alternative dependency management
    - uses: dingo-d/phpstan-wp-action@v1
    # ... then your own project steps ...